version: '3'

services:

  fsm-hub:
    image: lwzm/fsm-hub:postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      REDIS: redis://redis
    ports:
      - 1024:1024
    depends_on:
      - postgres
      - redis

  postgrest:
    image: lwzm/postgrest
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      PGRST_DB_URI: postgres://postgres/
      PGRST_DB_ANON_ROLE: postgres
    depends_on:
      - postgres
    ports:
      - 3000:3000

  postgres:
    image: postgres:alpine
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command:
      - --save
      - ''
    volumes:
      - /etc/localtime:/etc/localtime:ro
