version: '3'

services:

  crud:
    image: lwzm/crud
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgrest
    ports:
      - 8080:80

  fsm-hub:
    image: lwzm/fsm-hub:postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./database.yaml:/home/database.yaml:ro
    environment:
      REDIS: redis://redis
    ports:
      - 1024:1024
    depends_on:
      - postgres
      - redis

  postgrest:
    image: lwzm/postgrest
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      PGRST_DB_URI: postgres://postgres/
      PGRST_DB_ANON_ROLE: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    command:
      - --save
      - ''
    volumes:
      - /etc/localtime:/etc/localtime:ro
