version: '3.7'

services:

  crud:
    image: lwzm/crud
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - postgrest
    ports:
      - 8080:80

  fsm-hub:
    image: lwzm/fsm-hub:postgres
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      DB: '{"provider": "postgres", "host": "postgres", "user": "postgres"}'
    ports:
      - 1024:80
    depends_on:
      - postgres

  postgrest:
    image: lwzm/postgrest
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      PGRST_DB_URI: postgres://postgres/
      PGRST_DB_ANON_ROLE: postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./postgres:/var/lib/postgresql/data
